baseurl = "https://hoverzzzisa.ninja/"
title = "HoVeRzzz"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

publishDir = "docs"

paginate = 20

disqusShortname = "hoverzzz"

[markup.highlight]
style = "github-dark"

[params]
  author = "HoVeRzzz"
  info = "Technology and Fitness Enthusiast"
  description = "HoVeRzzz's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/pfp.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/imges/favicon-32x32.png"
  favicon_16 = "/imges/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/HoVeRzzz"
#[[params.social]]
#  name = "Gitlab"
#  icon = "fa fa-gitlab fa-2x"
#  weight = 2
#  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Youtube"
  icon = "fa fa-youtube fa-2x"
  weight = 3
  url = "https://www.youtube.com/c/HoVeRzzz"

# Menu links

[[menu.main]]
  name = "Products"
  weight = 1
  url  = "products/"

[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"

[[menu.main]]
  name = "Links"
  weight = 3
  url  = "links/"

[[menu.main]]
  name = "Contact"
  weight = 4
  url  = "contact/"

[[menu.main]]
  name = "Donate"
  weight = 5
  url = "donate/"

[[menu.main]]
  name = "About Me"
  weight = 6
  url = "about/"
